Avoid implicit array -> scalar conversion in tests
With numpy 2.4, it complains:

TypeError: only 0-dimensional arrays can be converted to Python scalars